name = "BaseDefense"
default_targets = ["macos", "win64"]
build_directory = "makelove-build"

love_files = [
    "+**/*",
    "-makelove-build/**",
    "-makelove.toml",
    "-.git/**",
    "-Notes/**",
    "-binaries/**",
]

[win64]
love_binaries = "binaries/win64"
