name = "BaseDefense"
default_targets = ["macos"] # win64 disabled due to local metadata error
build_directory = "makelove-build"

love_files = [
    "+**/*",
    "-makelove-build/**",
    "-makelove.toml",
    "-.git/**",
    "-Notes/**",
]
