name = "BaseDefense"
default_targets = ["macos", "win64"]
build_directory = "makelove-build"

love_files = [
    "+**/*",
    "-**/makelove-build/**",
    "-**/binaries/**",
    "-**/.git/**",
    "-**/Notes/**",
    "-**/makelove.toml",
]

[win64]
love_binaries = "binaries/win64"
