local EnemyIndex = {
    {
        id = "Grunt",
        type = "Grunt",
        class = require("Enemies.Enemy"),
        tier = 0,
        spawnCost = 10,
        spawnWeight = 1,
        maxHp = 100,
        damage = 10,
        speed = 25,
        color = {1, 0, 0, 1}, -- Red
        shape = "rectangle",
        size = 20,
        types = { enemy = true, red = true },
        baseSpawnDelay = 1,
        description = "Nothing special about this guy...",
        mutations = {}
    },
    {
        id = "Scout",
        type = "Scout",
        class = require("Enemies.Enemy"),
        tier = 0,
        spawnCost = 10,
        spawnWeight = 1,
        maxHp = 50,
        damage = 10,
        speed = 90,
        color = {1, 1, 0, 1}, -- Yellow
        shape = "rectangle",
        size = 15,
        types = { enemy = true, yellow = true },
        baseSpawnDelay = 0.5,
        description = "Fast, but fragile.",
        mutations = {}
    },
    {
        id = "Critter",
        type = "Critter",
        class = require("Enemies.Enemy"),
        tier = 0,
        spawnCost = 3,
        spawnWeight = 4,
        maxHp = 25,
        damage = 5,
        speed = 28,
        color = {0, 1, 0, 1}, -- Green
        shape = "rectangle",
        size = 12,
        types = { enemy = true, green = true },
        baseSpawnDelay = 0.2,
        description = "You'll never find just one",
        mutations = {}
    },
    {
        id = "Drone",
        type = "Drone",
        class = require("Enemies.TurretDebuffer"),
        tier = 0,
        spawnCost = 15,
        spawnWeight = 0.7,
        maxHp = 150,
        damage = 10,
        speed = 23,
        color = {0, 1, 1, 1}, -- Cyan/Blue
        shape = "rectangle",
        size = 20,
        types = { enemy = true, blue = true },
        baseSpawnDelay = 1.0,
        numTargets = 1,
        debuffStacks = 999,
        debuffDuration = nil,
        debuffFrequency = 4.0,
        stickyTargets = true,
        debuffStat = "fireRate",
        debuffAmount = -0.01,
        description = "Reduces turret efficiency with debuffs.",
        mutations = {}
    },
    {
        id = "Soldier",
        type = "Soldier",
        class = require("Enemies.Enemy"),
        tier = 1,
        spawnCost = 20,
        spawnWeight = 0.6,
        maxHp = 200,
        damage = 12,
        speed = 22,
        color = {1, 0, 0, 1}, -- Red
        shape = "soldier",
        size = 22,
        types = { enemy = true, red = true, armour = true },
        baseSpawnDelay = 1.0,
        affinities = {
            normal = 0.75,
            explosive = 0.75
        },
        description = "A sturdy combatant with light armour.",
        mutations = {}
    },
    {
        id = "Sapper",
        type = "Sapper",
        class = require("Enemies.Enemy"),
        tier = 1,
        spawnCost = 25,
        spawnWeight = 0.8,
        maxHp = 40,
        damage = 30,
        speed = 110,
        color = {1, 0.8, 0, 1}, -- Orange-Yellow
        shape = "rectangle",
        size = 12,
        types = { enemy = true, yellow = true, sapper = true },
        baseSpawnDelay = 0.4,
        description = "Fragile, fast enemy that deals extreme damage if it reaches the base.",
        mutations = {}
    },
    {
        id = "Broodmother",
        type = "Broodmother",
        class = require("Enemies.Spawner"),
        tier = 1,
        spawnCost = 50,
        spawnWeight = 0.2,
        maxHp = 250,
        damage = 15,
        speed = 15,
        color = {0, 1, 0, 1}, -- Green
        shape = "rectangle",
        size = 24,
        types = { enemy = true, green = true, spawner = true },
        baseSpawnDelay = 1.5,
        spawnAmount = 3,
        spawnFrequency = 6,
        spawnReference = "Critter",
        description = "Hatches Critters.",
        mutations = {}
    },
    {
        id = "Guardian",
        type = "Guardian",
        class = require("Enemies.Guardian"),
        tier = 1,
        spawnCost = 30,
        spawnWeight = 0.5,
        maxHp = 200,
        damage = 10,
        speed = 18,
        color = {0, 0.4, 1, 1}, -- Blue
        shape = "rectangle",
        size = 22,
        types = { enemy = true, blue = true, support = true },
        baseSpawnDelay = 1.0,
        description = "Provides a damage reduction aura to nearby allies.",
        hasAura = true,
        grantsShield = false,
        auraMult = -0.15,
        mutations = {
            { id = "blueguardian_shield", name = "Shield Granter", description = "Guardian now also grants shields to nearby allies.", modifiers = { grantsShield = { set = true } }, target = "Guardian" }
        }
    },
    {
        id = "Captain",
        type = "Captain",
        class = require("Enemies.Captain"),
        tier = 2,
        spawnCost = 35,
        spawnWeight = 0.5,
        maxHp = 250,
        damage = 10,
        speed = 20,
        color = {0, 0.4, 1, 1}, -- Blue
        shape = "rectangle",
        size = 22,
        types = { enemy = true, blue = true, support = true },
        baseSpawnDelay = 1.0,
        targets = 1,
        range = 120,
        clearCooldown = 3.0,
        description = "Periodically clears debuffs on nearby allies.",
        mutations = {}
    },
    {
        id = "PortalMaster",
        type = "PortalMaster",
        class = require("Enemies.PortalMaster"),
        tier = 2,
        spawnCost = 35,
        spawnWeight = 0.5,
        maxHp = 200,
        damage = 10,
        speed = 22,
        color = {1, 0.9, 0, 1}, -- Yellow
        shape = "rectangle",
        size = 22,
        types = { enemy = true, yellow = true, support = true },
        baseSpawnDelay = 1.0,
        targets = 1,
        range = 120,
        teleportDistance = 25,
        teleportCooldown = 5.0,
        description = "Periodically teleports nearby allies forward.",
        mutations = {}
    },
    {
        id = "Medic",
        type = "Medic",
        class = require("Enemies.Medic"),
        tier = 2,
        spawnCost = 35,
        spawnWeight = 0.5,
        maxHp = 220,
        damage = 10,
        speed = 20,
        color = {1, 0.2, 0.2, 1}, -- Red
        shape = "rectangle",
        size = 22,
        types = { enemy = true, red = true, support = true },
        baseSpawnDelay = 1.0,
        targets = 1,
        range = 150,
        regenAmount = 10,
        description = "Attaches to a nearby ally and heals them over time.",
        mutations = {}
    },
    {
        id = "Slime",
        type = "Slime",
        class = require("Enemies.Duplicator"),
        tier = 2,
        spawnCost = 25,
        spawnWeight = 0.5,
        maxHp = 100,
        damage = 15,
        speed = 22,
        color = {0.1, 0.9, 0.3, 1}, -- Green
        shape = "diamond",
        size = 18,
        types = {enemy = true, green = true, duplicator = true},
        affinities = {fire = 1.2}
        baseSpawnDelay = 1.0,
        description = "A cellular green slime that divides upon death.",
        mutations = {}
    },
    {
        id = "Tank",
        type = "Tank",
        class = require("Enemies.Tank"),
        tier = 5,
        spawnCost = 55,
        spawnWeight = 0.1,
        maxHp = 2500,
        damage = 50,
        speed = 12,
        color = {1, 0.2, 0.2, 1}, -- Red
        shape = "tank",
        size = 30,
        types = { enemy = true, red = true, tank = true },
        affinities = { heal = 1.5 },
        baseSpawnDelay = 2.5,
        description = "Slow and heavy. Can soak up massive damage and takes increased healing.",
        mutations = {}
    }
}

return EnemyIndex
